<a href="https://colab.research.google.com/github/pravin-pandey/brainwaves/blob/master/svm_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# importing required libraries 
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
  
# reading csv file and extracting class column to y. 
x = pd.read_excel("sleep_work_dataset.xlsx") 
a = np.array(x) 
y  = a[:,5] # classes having 0 and 1 
  
# extracting two features 
x = np.column_stack((x.avg_wrk_hrs_per_day,x.sleep_after_work,x.eeg_signal_in_Hz)) 
x.shape # 550 samples and 3 features 
  
print (x),(y) 

[[ 8.   0.   5.2]
 [ 9.   1.  13. ]
 [ 8.5  0.   9.8]
 ...
 [10.   1.   6.4]
 [ 8.   0.   8.5]
 [ 8.   1.   9.3]]


(None, array([ 5.2, 13. ,  9.8,  7.8, 13.5,  5.3,  9.2, 12.9, 13.6,  7.6,  4.3,
         6.4,  5.5,  9.5,  9.4,  5.9,  7.6,  6.4,  9.8,  7.6,  4.9,  8.8,
         6.7,  5.2,  6.9,  6.4,  5.1,  9. ,  7.1,  6.2,  9.5,  4.3,  9.8,
         7.5, 12.4,  5.6, 11.9,  7.8,  9.5, 10.5,  6.5,  8.9,  8.7,  6.5,
         9.5,  8.4, 12.5, 11.2,  9.8,  7.5,  9.1,  5.8,  5.6,  9.8,  5.1,
         9. ,  7.1,  6.2,  9.5,  4.3,  9.8,  7.5, 12.4,  5.6, 11.9,  7.8,
         9.5, 10.5,  6.5,  8.9,  8.7,  6.5,  9.5,  8.4, 12.5, 11.2,  9.8,
         7.5,  9.1,  5.8,  5.6,  9.8,  5.2, 13. ,  9.8,  7.8, 13.5,  5.3,
         9.2, 12.9, 13.6,  7.6,  4.3,  6.4,  5.5,  9.5,  9.4,  5.9,  7.6,
         6.4,  9.8,  7.6,  4.9,  8.8,  6.7,  5.2,  6.9,  6.4,  5.1,  9. ,
         7.1,  6.2,  9.5,  4.3,  9.8,  7.5, 12.4,  5.6, 11.9,  7.8,  9.5,
        10.5,  6.5,  8.9,  8.7,  6.5,  9.5,  8.4, 12.5, 11.2,  9.8,  7.5,
         9.1,  5.8,  5.6,  9.8,  5.1,  5.2, 13. ,  9.8,  7.8, 13.5,  5.3,
         9.2, 12.9, 13.6,  7.6, 

In [0]:
# import support vector classifier 
from sklearn.svm import SVR # "Support Vector Regressor because we have to use float values" 
clf = SVR(kernel='linear') 
  
# fitting x samples and y classes 
clf.fit(x, y) 

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
  gamma='auto_deprecated', kernel='linear', max_iter=-1, shrinking=True,
  tol=0.001, verbose=False)

In [0]:
clf.predict([[10, 0, 13]]) 

array([9.97741897])