<a href="https://colab.research.google.com/github/pravin-pandey/brainwaves/blob/master/svm_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt  
%matplotlib inline

In [0]:
sw = pd.read_excel("sleep_work_dataset.xlsx")  

In [0]:
sw.shape 

(550, 6)

In [0]:
sw = sw.drop(columns="mentally_stressed")
sw.head()  

ID  avg_wrk_hrs_per_day  sleep_after_work  sleep_loss_diagnosed  \
0   1                  8.0                 0                     0   
1   2                  9.0                 1                     0   
2   3                  8.5                 0                     0   
3   4                 15.0                 1                     1   
4   5                 10.0                 1                     0   

   eeg_signal_in_Hz  
0               5.2  
1              13.0  
2               9.8  
3               7.8  
4              13.5

In [0]:
X = sw.drop('sleep_loss_diagnosed', axis=1)  
y = sw['sleep_loss_diagnosed'] 

In [0]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)  

In [0]:
#linear kernel
from sklearn.svm import SVC  
svclassifier = SVC(kernel='linear')  
svclassifier.fit(X_train, y_train) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [0]:
y_pred = svclassifier.predict(X_test) 

In [0]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred)) 

[[51  0]
 [59  0]]
              precision    recall  f1-score   support

           0       0.46      1.00      0.63        51
           1       0.00      0.00      0.00        59

   micro avg       0.46      0.46      0.46       110
   macro avg       0.23      0.50      0.32       110
weighted avg       0.21      0.46      0.29       110



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [0]:
#Gaussian kernel
from sklearn.svm import SVC  
svclassifier = SVC(kernel='rbf')  
svclassifier.fit(X_train, y_train) 

/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [0]:
y_pred = svclassifier.predict(X_test) 

In [0]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred)) 

[[46  5]
 [52  7]]
              precision    recall  f1-score   support

           0       0.47      0.90      0.62        51
           1       0.58      0.12      0.20        59

   micro avg       0.48      0.48      0.48       110
   macro avg       0.53      0.51      0.41       110
weighted avg       0.53      0.48      0.39       110



In [0]:
#Sigmoid kernel
from sklearn.svm import SVC  
svclassifier = SVC(kernel='sigmoid')  
svclassifier.fit(X_train, y_train)  

/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='sigmoid', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [0]:
y_pred = svclassifier.predict(X_test) 

In [0]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))  

[[51  0]
 [59  0]]
              precision    recall  f1-score   support

           0       0.46      1.00      0.63        51
           1       0.00      0.00      0.00        59

   micro avg       0.46      0.46      0.46       110
   macro avg       0.23      0.50      0.32       110
weighted avg       0.21      0.46      0.29       110



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
